### ISSUE TITLE
WP Chosen conflicts with SendGrid Dropdowns

### ISSUE THREAD

**Issue by ryanjbonnell** [stuttter/wp-chosen#11]
Tested using WP Chosen 3.1.0, [SendGrid][1] 1.11.4 and WordPress 4.8 (no other plugins active).

_Note: SendGrid bundles Select2 4.0.3:_

![screen shot 2017-07-28 at 12 53 01 pm](https://user-images.githubusercontent.com/133372/28734063-ee56abd8-7393-11e7-9a2b-a6ac97438098.png)

[1]: https://wordpress.org/plugins/sendgrid-email-delivery-simplified/

**Comment by JJJ** [comment]
Hey @ryanjbonnell. Sorry the years of waiting. Do you know if this is still a problem?

**Comment by ryanjbonnell** [comment]
Yes, this is still an issue.

The same problem exists using WP Chosen 3.0.0, SendGrid 1.11.8 and WordPress 5.2.3.

![Screen Shot 2019-09-27 at 3 33 00 PM](https://user-images.githubusercontent.com/133372/65805869-1fd74600-e13c-11e9-8160-70330ccc028b.png)

**Comment by JJJ** [comment]
Going to be fixed in 6.0.0.
