### ISSUE TITLE
Breaks Front Page Displays Option

### ISSUE THREAD

**Issue by robneu** [stuttter/wp-chosen#2]
I'm only testing this locally, but here's a gif of what happens when trying to set a static front page when one hasn't been set before enabling WP Chosen:

![qjhaasmwa3](https://cloud.githubusercontent.com/assets/2184093/11448979/cd042a5e-9533-11e5-961d-dfacf94a12ac.gif)

This is on WP `4.3.1` and I'm not seeing any JS errors in the console. If there's anything else I can provide that would be helpful for debugging please let me know.

**Comment by johnjamesjacoby** [comment]
That's a bummer. It looks like the Chosen library doesn't listen for disabled checks on the parent select element.

I'll look at fixing this for a future release.

**Comment by johnjamesjacoby** [comment]
Fixed in ddb03cb.
