### ISSUE TITLE
WP Chosen conflicts with Stream Plugin's use of Select2 JavaScript Library

### ISSUE THREAD

**Issue by ryanjbonnell** [stuttter/wp-chosen#7]
Tested using [WP Chosen](https://wordpress.org/plugins/wp-chosen/) 2.1.0, [Stream](https://wordpress.org/plugins/stream/) 3.2.0 and [WordPress](https://wordpress.org/) 4.7.4.

![WordPress Stream Records](https://cloud.githubusercontent.com/assets/133372/25500298/59b10d7c-2b43-11e7-8b5a-488fcfcd43f6.png)

![WordPress Stream Exclusion Settings](https://cloud.githubusercontent.com/assets/133372/25500307/65b2a888-2b43-11e7-9734-485f9d27701a.png)

**Comment by JJJ** [comment]
Sorry about this. I imagine WP Chosen should specifically not target select boxes that are already targeted by Select2.

I'll look into this in the next release. Thanks for reporting this here!

**Comment by JJJ** [comment]
I can reduce the conflict with Stream down to everything but this 1 drop-down:

<img width="1091" alt="screen shot 2017-06-22 at 1 20 05 pm" src="https://user-images.githubusercontent.com/88951/27449315-947327c0-574d-11e7-8deb-5434d9c96718.png">

See above for pull-requests to address that. 🙏
