### ISSUE TITLE
WP Chosen conflicts with Post and Page Meta Box Dropdowns

### ISSUE THREAD

**Issue by ryanjbonnell** [stuttter/wp-chosen#9]
Tested using WP Chosen 3.0.0 and WordPress 4.7.5 (no other plugins active).

![screen shot 2017-06-01 at 2 21 29 pm](https://cloud.githubusercontent.com/assets/133372/26701357/a7f62a8c-46d5-11e7-9dd3-602664fb0244.png)

**Comment by jb510** [comment]
I'm still seeing this exact behavior, WP 4.8.2, WP Chosen 3.0.0

What odd, is I don't think WP Chosen should even touch these dropdown as there are only a few items in each.

![2017-10-10 at 4 15 pm](https://user-images.githubusercontent.com/801241/31415125-45e7411a-add6-11e7-8a8c-89bda2d14c1e.png)
